name: Bug report
description: Report a reproducible problem
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for filing a report. Please provide enough detail to reproduce."

  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: Sidebar overlaps on mobile width 390px
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run npm run start
        2. Open on 390x844 viewport
        3. Toggle sidebar
        4. Observe overlap
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: Android 14, Chrome 121, Node 20
