name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: input
    id: summary
    attributes:
      label: Feature summary
      placeholder: Add dark mode mobile contrast tuning
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem this solves
      placeholder: Describe pain point or limitation
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      placeholder: Describe expected behavior and UX
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
